[lint]
description = "lint project"
dependencies = "mypy"
commands = "mypy --ignore-missing-imports ."

[format]
description = "format project"
dependencies = "ruff"
commands = ["ruff check --fix", "ruff format --line-length=100 ."]

[test]
description = "test project"
dependencies = ["pytest", "pytest-cov"]
commands = ["pytest -vv --disable-warnings -s --cache-clear"]

[no-deps]
commands = "echo 'Hello world'"

[run]
suite = ["lint", "format", "test", "no-deps"]